# Generated by Django 3.1.4 on 2021-07-31 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210731_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment_course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam_course_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 12, 4, 18, 852080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 12, 4, 18, 849433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 31, 12, 4, 18, 855476, tzinfo=utc)),
        ),
    ]
