# Generated by Django 3.1.4 on 2021-08-02 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210731_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_score',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 12, 37, 50, 461539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 12, 37, 50, 459791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 12, 37, 50, 462758, tzinfo=utc)),
        ),
    ]
